apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-clothig-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-clothig-model
  template:
    metadata:
      labels:
        app: tf-serving-clothig-model
    spec:
      containers:
      - name: tf-serving-clothig-model
        image: zoomcamp-10-model:xception-v4-001
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8500
